server:
  port: ${SERVER_PORT:8080}

votify:
  admin:
    password: ${VOTIFY_ADMIN_PASSWORD:admin123}

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/votify}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:admin}
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        "[format_sql]": true
  jackson:
    default-property-inclusion: non_null
